service: alexa-rota # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-1:*:*"

functions:
  handleRequest:
    handler: main.handleRequest
    events:
      - alexaSkill
  
resources:
  Resources:
    alexaRota:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: alexa-rota
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1